### ISSUE TITLE
Give me a second to finish my query before telling me it's invalid

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-hexeditor#110]
Testing https://github.com/microsoft/vscode/issues/103176

Any single digit hex search query is invalid, so it's impossible to type a query without getting a red blink. Maybe just debounce the validation so it only complains a second after I finish typing.

**Comment by lramos15** [comment]
Single character hex strings are now valid so that fixes the majority of the issues. Do you feel I should still debounce it for chance the user types an invalid character? I feel like I would rather know sooner rather than later that my query is invalid especially because it doesn't tell you why so you lose the ability to find out which character caused the invalid message.

**Comment by roblourens** [comment]
I think that if a single hex character is a valid search, then that would resolve my complaint
