### ISSUE TITLE
Editor flashes on save of watched file

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-hexeditor#129]
Testing https://github.com/microsoft/vscode/issues/103175

When an external editor saves the file, the hex editor flashes, even if nothing changed.

**Comment by lramos15** [comment]
This is due to the fact that we would have to diff the viewport with the file contents that we just received from the file watcher to see if there are any changes. Right now we just throw out the viewport and re-render it hence the flash. I think this optimization would come with changing the contents of the cells based on the changes instead of re-rendering the viewport.
