### ISSUE TITLE
Column headers and decoded text are vertically aligned differently

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#131]
![image](https://user-images.githubusercontent.com/2193314/88414328-87c4e000-cd91-11ea-8fb3-a07a861f3a17.png)

![image](https://user-images.githubusercontent.com/2193314/88414354-927f7500-cd91-11ea-8171-4a4783321f68.png)

**Comment by lramos15** [comment]
@mislori This is caused by mixing non monospace and monospace fonts along with trying to keep headers 11px to match the editor. I have made all headers monospace and made them respect the editor font size setting as this fixes alignment issues like this which get further exacerbated when font sizes increase like #122. Let me know if there's a better solution :)

**Comment by Tyriar** [comment]
> I have made all headers monospace

It looks _so much_ better when they're not monospace. You should be able to get better alignment using CSS, try `line-height`.

**Comment by lramos15** [comment]
Thanks for the suggestion. I have went back to non monospace and used lineheight 
![image](https://user-images.githubusercontent.com/4544166/88554057-04ef8f80-cff4-11ea-8293-1c475f259bb7.png)
