### ISSUE TITLE
readonly mode

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode-hexeditor#180]
A readonly mode is not only useful for debugging: https://github.com/microsoft/vscode-hexeditor/issues/70#issuecomment-658872773
Also when opening files from /usr for example.

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/issues/91555 proposed an api that should help custom editors detect when they are viewing a resource form a readonly file system

**Comment by Tyriar** [comment]
I would like this too but for a different use case; Since I don't generally want to edit via the hex editor, only view files, I worry about accidentally editing a file and corrupting it.

**Comment by scsteel** [comment]
There are two aspects to this:

1. If the file being displayed is read-only (read-only filesystem, or has read-only attribute), then it is useful for the UI to reflect this and prevent the user from initiating edits (since they can't be saved).
2. However, if the file being displayed is not read-only, then the user may nonetheless wish to use hexEditor as a viewer, with editing disabled so they don't accidently change the contents.

**Comment by Trass3r** [comment]
>     1. If the file being displayed is read-only (read-only filesystem, or has read-only attribute), then it is useful for the UI to reflect this and prevent the user from initiating edits (since they can't be saved).

Yeah some editors use a little lock next to the filename in the tab header.

**Comment by connor4312** [comment]
This is now supported
