### ISSUE TITLE
Hex editor endianness dropdown doesn't feel native

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-hexeditor#318]
Testing [#138092](https://github.com/microsoft/vscode/issues/138092)

![image](https://user-images.githubusercontent.com/30305945/144102768-c540b184-85ad-49fd-be97-a1b579b3960f.png)

1. The rounded corners on the dropdown list don't seem to match 
2. List items have different height than the currently selected element

I'd expect it to look like this: https://github.com/microsoft/vscode-webview-ui-toolkit/tree/main/src/dropdown

**Comment by connor4312** [comment]
It's a native `<select>` element, while the webview UI toolkit version is (ironically) not native 😛 

While it can use a little polish, the data inspector is a separate view and I don't really anticipate using the webview UI toolkit for it since the styling we need is super minimal. But if we do adopt it we'll get a Code-like dropdown for free.
