### ISSUE TITLE
Caps Lock, Ctrl + F can't open "find text" window

### ISSUE THREAD

**Issue by IsBenben** [microsoft/vscode-hexeditor#535]
- VS Code 1.85.2.
- Extension 1.9.14.

**Comment by connor4312** [comment]
Can you "toggle screencast mode" and share a gif so we can see the keys VS Code gets?

/gifPlease

**Comment by IsBenben** [comment]
![Recording 2024-09-20 at 21 07 38](https://github.com/user-attachments/assets/55dd6528-cbd5-408e-bc19-6a7c5ed90d47)

**Comment by stamatiad** [comment]
I had the same issue, but it was resolved by invoking the Ctrl-F, after first focusing on the text part of the hex editor (on the right side), rather than in the hex part. So:
1. Click somewhere on the text part,
2. Ctrl-F to search.
3. Choose 'Binary mode' on the search panel to search in the hex part of the editor.
Hope this resolves the issue for you as well.

Cheers.

**Comment by tomilho** [comment]
I'll look into this. I don't think it should be a complex fix
