### ISSUE TITLE
Scrolling seems to be broken on linux

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode-hexeditor#57]
Testing https://github.com/microsoft/vscode/issues/101307

1. Scrolling feels very "slow" as compared to other editors
2. Dragging the scrollbar seems to have a parallax effect. I could not get to the bottom of my file.

![hexeditor](https://user-images.githubusercontent.com/8235156/86168581-6a7c5900-bae6-11ea-911d-1703a82a72af.gif)

**Comment by sandy081** [comment]
Also same on Mac - seems broken when I open a large file - for eg [checker.ts](https://raw.githubusercontent.com/microsoft/TypeScript/master/src/compiler/checker.ts)

**Comment by lszomoru** [comment]
Same on Windows.

**Comment by lramos15** [comment]
[hexeditor-1.1.0.zip](https://github.com/microsoft/vscode-hexeditor/files/4858447/hexeditor-1.1.0.zip)
Here's a new VSIX (change from .zip to .vsix). I believe that I fixed the issue, but if I haven't please let me know. The scroll should be faster but you will see a lot of blank frames that's because even with a document which is 18mb the data layout isn't very compact and you end up with over 1 mile of scrollable content. This is difficult with the scrollbar as we need to keep the scrollbar thumb large enough to grab meaning that move the scrollbar thumb one pixel might need to scroll the document 1000px leading to the blank frames you see as everything loads in.
