### ISSUE TITLE
Editor should be responsive

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-hexeditor#6]
Testing https://github.com/microsoft/vscode/issues/98980

It seems to require quite a wide editor for everything to fit:

![image](https://user-images.githubusercontent.com/22350/83533906-73cad380-a4f0-11ea-8d71-7606202c4246.png)

**Comment by FabianoGK** [comment]
Since this issue seems to be related to the style of the editor window, I would like to suggest:

1) removing the word "Memory" from "Memory Offset";
2) move "Data Inspector" panel to the right;
3) allow "Data Inspector" panel to be collapsed;
4) reduce padding around characters on the "Decoded Text" panel;
5) have another dropdown on "Data Inspector" to adjust the base for all integer numbers (dec/hex/oct/bin);
6) have a way to configure how many bytes to show per line.

HxD is really great at allowing any number of bytes per line. It even has the ability to adapt the number of bytes per line to fit the width of the window.

The other suggestions were also inspired on HxD features.

**Comment by antoniovazquezblanco** [comment]
Here I would like to add my two cents, I hope it helps:
- At first the hex editor is a bit weird because it colapses the file tree view while the text editor does not do that. I would suggest trying to mimick the default behaviour of the text editor and not collapse the lateral view unless the user explicitly does so...
- I really agree with @FabianoGk when talking about reducing extra words: "Memory Offset" -> "Offset" would be great.
- I would panelize the "Data inspector". Maybe converting it to a panel that could be moved to the bottom (same as the console) or to a side or customizing where it can be placed helps with the issue of fitting multiple sized screens... Maybe one could even think of a lateral button like VCS does but this seems less intuitive for myself.
- Integrate with the native search funciton maybe. I don't know if this is possible but it would be awesome to be able to integrate with the native search solutions instead of you having to implement your own...

**Comment by connor4312** [comment]
We've since change the editor design a bit. The Data Inspector turns in a hover on narrow screens, and the width of the inspector is customizable (though we don't want the width to be 'responsive' since the number of bytes per row is important)
